on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: hello-world-job
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4

      - name: greet
        id: hello
        uses: ./.github/actions/hello-world-docker-action
        with:
          who-to-greet: "Romeo"

      - name: get-output-time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      
      - name: print-secrets
        run: |
          echo "${{ secrets.SECRET_API_KEY_1 }}"
          echo "${{ secrets.SECRET_API_KEY_2 }}"
          echo "Done printing secrets!"
